[build]
  command = "npm run build"  # Or "yarn build"
  publish = "dist"  # Or any directory where the built files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
