[build]
  # The build directory for React apps
  publish = "build"
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html (for SPAs)
  from = "/*"
  to = "/index.html"
  status = 200