[build]
  # The build directory for React apps
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

redirects:
  - force: true
    from: /*
    status: 200
    to: /index.html
redirectsOrigin: config
